name: Deploy Sentinel Artifacts

on:
  push:
    branches: [ main ]
    paths:
      - 'Detections/**'
      - 'Hunting/**'
      - 'Workbooks/**'
      - 'Playbooks/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Analytics Rules
        run: |
          for file in ./Detections/*.json; do
            echo "Deploying $file"
            az sentinel alert-rule create \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_WORKSPACE }} \
              --rule-file $file
          done
